import type {Metadata} from "next";
// import localFont from "next/font/local";
import "./globals.css";
import "./theme-config.css"
import '@radix-ui/themes/styles.css';
import NavBar from "@/app/NavBar";
import {Theme, ThemePanel} from "@radix-ui/themes";

/*const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});*/

import { Inter } from 'next/font/google';

const inter = Inter({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-inter'
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={inter.variable}>
        <body>
        <Theme
            appearance="light"
            accentColor="violet"
            panelBackground="solid"
        >
            <NavBar/>
            <main className="px-5">
                {children}
            </main>
            {/*<ThemePanel/>*/}
        </Theme>
        </body>
        </html>
    );
}
